name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85a59f5d20bbc9fb5bab1f25f5e3f9147c16a83e9d50a1b289338ce03476cef4"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
