name = ":3pack"
author = "emilia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f0836fc923d9b646c122888449b4b07576a04fa2cc30bd8dd1dd24ee28ff0c1"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
