name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f69da2855b46830b4d3c263087d8b032e41260b6ec52987caa290838ec5e62ce"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
