name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94e976abe4365e67aa0f5992b38c71d8f167199fd95101457ea8ea25213e9765"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
