name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8240d5bd2b7f673e302facd8c2021308cd982cc53c199d90a292552afe345370"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
