name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d6360d848f19d04c2e5e3997ed939ff689eb793d013619aab35dac3f1cfa3c9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
