name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "546af0c635e011e8fa65cd2db155519f8684656b9d11407974d382eeccd9f4a2"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
