name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f78d5c96bea80de954535ac83df659988aa08cdd4f375b7d201948347e901718"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
