name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4b7d72b851837df1163e90c31ed502d8098f6a90c2919a621c47577ae09bc5e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
