name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c985e6addcfe6724a75e11027df45336fa3ea5e09ed742110a214cb04a3e084"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
