name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1718256d0550ba7b06d361ae26f1359ee5a96be312bdd5ba47fd6b5eacf7bf68"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
