name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "008310ceae96dacf88af86eef986ee83734f0d75d54e186540a983bea498eefa"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
