name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fb034ee744d93d049218f2158e1212322871d25f3ff0ce8d05a3ca5e9ea2f4e"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
