name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f7349e90898c29c7627b6641484b204f664fc5ef4d310f498b01aaa08c138d5"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
