name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f326af6b238ac58d14b4c93228fbbfdcdbabff81c5224ca1e7050949003d6a3"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
