name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "791517db4e436f7466f986a3cb5873eb4f02eeec0eecf0ac8766bf1d824dda8f"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
