name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9187d446837e48ef6d0cbce78520ab2e99cb5127bed8de0cf868911fec4c0406"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
