name = ":3pack"
author = "emilia"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9661928e8946cec4818ee1e074fcf7c9afabbb72f48d51a0fdecd3f57c0bf2c0"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"
