name = "huskraft"
author = "emiii :D"
version = "meow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "110c7bc2e583108b9367fa903feb7044ef3686c0392510eaa7419c2c6d4d81a9"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
