name = "huskraft"
author = "emiii :D"
version = "meow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bbf6ff0f4c129a3dd1fb44329097fae70e5a4a10816e90792d5c9f5103e9fc6"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
