name = "huskraft"
author = "emiii :D"
version = "meow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f2f084b809627e8df3cec53169b6a147c34e12b09808ecc97076a4ad292ba5d"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
