name = "huskraft"
author = "emiii :D"
version = "meow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3702e965fbd85ecec981086a6ee09e4899b360be11cf7b3fe739412b95cca1c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
