name = "huskraft"
author = "emiii :D"
version = "meow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3d3ec2a918937c95d93cfd825b3a73654484e1b63050db82a63b30f3a5b5b5c"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
