name = "huskraft"
author = "emiii :D"
version = "meow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c04e87b1396b3c07d9ea698c562149d602c23100da1b184f8b5e82a5b23dc36"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
