name = "huskraft"
author = "emiii :D"
version = "meow"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca016c1d4b863160004b40806750f1116c2914f9bc96e7604e29a04dc7bbb0f8"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
